### ISSUE TITLE
added support for column default value

### ISSUE THREAD

**Issue by zlwzxy1989** [yallie/pg_global_temp_tables#2]
Sorry for my poor English.I tried to add support for column default value and it looks work.
Changes are marked at the end of rows with `--HERE`.
Be free to merge to your repo if you think it`s OK.Sorry for not familiar with pull request.

create_permanent_temp_table
```
  -- generate the temporary table statement
  with pkey as
  (
    select cc.conrelid, format(E',
    constraint %I primary key(%s)', cc.conname,
      string_agg(a.attname, ', ' order by array_position(cc.conkey, a.attnum))) pkey
    from pg_catalog.pg_constraint cc
      join pg_catalog.pg_class c on c.oid = cc.conrelid
      join pg_catalog.pg_attribute a on a.attrelid = cc.conrelid and a.attnum = any(cc.conkey)
    where cc.contype = 'p'
    group by cc.conrelid, cc.conname
  )
  select format(E'\tcreate temporary table if not exists %I\n\t(\n%s%s\n\t)\n\ton commit drop;',
    v_table_name,
    string_agg(
      format(E'\t\t%I %s%s%s',--HERE
        a.attname,
        pg_catalog.format_type(a.atttypid, a.atttypmod),
        case when a.attnotnull then ' not null' else '' end,
        case when a.atthasdef = true then ' default ' || pg_get_expr(d.adbin, d.adrelid) else '' end--HERE
      ), E',\n'
      order by a.attnum
    ),
    (select pkey from pkey where pkey.conrelid = c.oid)) as sql
  into v_table_statement
  from pg_catalog.pg_class c
    join pg_catalog.pg_attribute a on a.attrelid = c.oid and a.attnum > 0
    left outer join pg_catalog.pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum--HERE
    join pg_catalog.pg_type t on a.atttypid = t.oid
  where c.relname = p_table_name and c.relpersistence = 't'
  group by c.oid, c.relname;

  -- generate the lists of columns
  select
    string_agg(a.attname, ', '),
    string_agg(format('%s', case when a.atthasdef = true then 'coalesce(new.' || a.attname || ', ' || pg_get_expr(d.adbin, d.adrelid) || ')' else 'new.' || a.attname end), ', '),--HERE
    string_agg(format('%I = new.%I', a.attname, a.attname), ', '),
    string_agg(format('%I %s', a.attname, pg_catalog.format_type(a.atttypid, a.atttypmod)), ', '),
    string_agg(format('%I = old.%I', a.attname, a.attname), ' and ')
  into
    v_all_column_list, v_new_column_list, v_assignment_list, v_cols_types_list, v_old_column_list
  from pg_catalog.pg_class c
    join pg_catalog.pg_attribute a on a.attrelid = c.oid and a.attnum > 0
    left outer join pg_catalog.pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum--HERE
    join pg_catalog.pg_type t on a.atttypid = t.oid
  where c.relname = p_table_name and c.relpersistence = 't';
```

**Comment by yallie** [comment]
Great! Thanks a lot :)

>Be free to merge to your repo if you think it`s OK. Sorry for not familiar with pull request.

That's actually very easy, no external tools involved, just the Github website.
Please follow these steps, so I can add your commit to the repository and list you as a contributor.

1. Click on the sql file in my repository to open the viewer.
2. Locate the `Edit` button in the top-right corner. Note the `Fork this project and edit the file` tooltip:

> ![image](https://user-images.githubusercontent.com/672878/40051312-ebc2af18-5842-11e8-8c86-2b7cbc477bbe.png)

3. Click the `Edit` button, and Github will fork the repository under your account.
4. Make your edits to the file and click the large `Commit changes button` below.
5. Now open the `Pull requests` tab and click the `New pull request` button to submit your PR:

> ![image](https://user-images.githubusercontent.com/672878/40051517-be289238-5843-11e8-85be-91e9b710f23e.png)

6. Add your comments or just click `Create pull request` to submit.

That's it, basically. Should take not more than a couple of minutes.

**Comment by zlwzxy1989** [comment]
Thank you very much for your detailed explanation.I've tried to create a pull request.Please see if it`s correct.

**Comment by yallie** [comment]
Great, thanks a lot!
And congrats with your first pull request :)

**Comment by yallie** [comment]
Would you mind adding a unit test for this feature?
The tests are defined in [pg_global_temp_tables_tests.sql](https://github.com/yallie/pg_global_temp_tables/blob/master/pg_global_temp_tables_tests.sql) file.
Just copy+rename an existing test, add some default values and check if it works.
The begin/exception code block is used for rolling back all the changes.
I hope the pattern is clear from the existing samples.

The tests use the tiny [PGUnit](https://github.com/adrianandrei-ca/pgunit) testing framework.
The framework is just a bunch of functions installed in the dedicated pgunit schema.
Here is a hint on running the unit tests for this library: [running the unit tests](https://github.com/yallie/pg_global_temp_tables#unit-tests).

**Comment by zlwzxy1989** [comment]
Got it.I'll try it tomorrow if have time.It's 23:41 now:)

**Comment by yallie** [comment]
No problem, good night! And thanks again for your contribution :)

**Comment by zlwzxy1989** [comment]
Sent a pull request.Please see the comment in the pull request.

**Comment by yallie** [comment]
Great, thank you!

>Sent a pull request.Please see the comment in the pull request.

Oh, looks like you've created a pull request to your own fork.
Let me see if I can re-target your pull request to my repository from it.

>Maybe I have some issues on setup pgunit. When run tests via pgunit,error is shown like:
>syntax error at or near "."

Regarding your comments — I don't see anything wrong with the unit test code.
Perhaps it's something related to locale and parsing number values?
What is the decimal point in your OS locale by the way?
Is it different from en-us "." decimal point?

**Comment by yallie** [comment]
Ok, I re-created the pull request so that it targets my repo and merged it.
I'll look into the unit test issue once I have the time.
I think it's a minor issue if the function executes just fine outside PGUnit.

Thanks a lot again! :)

**Comment by zlwzxy1989** [comment]
Sorry for the lack of konwledge of github...

> What is the decimal point in your OS locale by the way?
Is it different from en-us "." decimal point?

I'm using Japanese Windows 7,the decimal point is `.` so it may not be the problem...
I even tried to run an empty test case via PGUit but with no luck :(

Anyway thanks for your help on how to use pull request, and more thanks to your excellent library:)
